2025/02/20 13:26:31 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/online-users/ HTTP/1.1", upstream: "http://172.18.0.6:8000/api/users/online-users/", host: "localhost:8080", referrer: "http://localhost:8080/"
2025/02/20 15:57:10 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/users/online-users/ HTTP/1.1", upstream: "http://172.18.0.6:8000/api/users/online-users/", host: "localhost:8080", referrer: "http://localhost:8080/"
